### ISSUE TITLE
Your buttons lead to 404 errors

### ISSUE THREAD

**Issue by Baddaboo** [FamiKona/fn-react#6]
https://github.com/FamiKona/fn-react/blob/9732fcc0751bdd7b42aa6be42823d86a49ee5071/src/views/Land.js#L28

Don't use `<a href=... />` as they don't work with `react-router`. Use `<Link />` instead. Here's a [StackOverflow answer](https://stackoverflow.com/a/43986829) for more info

**Comment by ashgarr** [comment]
fixed in latest deploy

thanks @Baddaboo!
